### PR TITLE
Improves travis config

### PR DESCRIPTION
**Pull request by sagikazarmark**
It adds the following things:

* Test against PHP 7.0
* Test against the lowest dependencies
* Generate coverage only once
* Cleaner configuration

### CODE REVIEW

**Comment by lstrojny** [comment]
Awesome idea, can you check the build?

**Comment by sagikazarmark** [comment]
Of course, will do

**Comment by sagikazarmark** [comment]
I spent the last few hours with debugging the code on HHVM and PHP 7 with no success. It seems that there are some BC breaking changes in PHP 7 xmlrpc extension, but I couldn't find it in the source.

Seems like we have to do some more work to make this library HHVM and PHP 7 compatible.

Till then I would suggest merging this PR and opening separate issues/PRs.

**Comment by lstrojny** [comment]
Sounds good. Thanks!

**Comment by sagikazarmark** [comment]
Don't forget to merge develop into master (again)

**Pull request merged**
