### PR TITLE
Alpha for 1.0

### PR DESCRIPTION
**Pull request by lstrojny**
- Uses egeloen/http-adapter to support multiple HTTP clients
 - Cleaned up interfaces
  - `ClientInterface` is now small and nice
  - `CallClientInterface` is the contract for `call()`
  - `MulticallInterface` is the contract for `multicall() : MulticallBuilderInterface`
 - Renamed `Multicall` to `MulticallBuilder`, introduced `MulticallBuilderInterface`
 - Uses PSR-4

### CODE REVIEW

**Comment by sagikazarmark** [comment]
The HTTP adapter package has a new version: 0.7. It comes with a lot of improvements (which I really like). Bumping the version might make sense.

Also, an alpha release should come out soon. ;)

**Comment by lstrojny** [comment]
Can you open a PR for the 0.7 bump?

**Comment by sagikazarmark** [comment]
I looked at the release and it seems it is not really complete. Some repositories are required to be manually included. IMO we don't need it right now, so we should probably only bump a version when it is stable enough. When the adapter package reaches 1.0, we could just rely on `~1.0`.

**Comment by sagikazarmark** [comment]
Maybe you could delete the develop branch as well to prevent further PRs. An alpha release maybe?

**Comment by lstrojny** [comment]
Alright, 1.0.0-alpha1 is tagged

**Comment by sagikazarmark** [comment]
Awesome!

**Pull request merged**
